### ISSUE TITLE
About uppasd installation issues

### ISSUE THREAD

**Issue by code-whale** [UppASD/UppASD#11]
Dear UppASD team,
Hello, I would like to ask you how to install the uppasd software. I downloaded your code base, unzip it, run the terminal in the folder, and enter ````./setup_UppASD.sh````,Then I typed ````make gfortran-osx````, but the error as shown in the figure was returned. Can you tell me what to do, thanks for your help!
![image](https://user-images.githubusercontent.com/61874432/97430305-a966d200-1953-11eb-8c74-b651e53d2b43.png)
I am using MacOS 10.15.6

**Comment by anbergman** [comment]
Hi @code-whale, it looks from the log that you are missing a fortran compiler on your system,
For macOS, I recommend to use [https://brew.sh/](url) for that. With `brew` installed, you can then run `brew install gcc` in order to get the needed compilers (which would be `gfortran` in this case).

**Comment by code-whale** [comment]
@anbergman ,Thank you for your reply, but I clicked on the link attached to your reply and the following interface was displayed. It seems that the content of this link has disappeared. Can you tell me what to do next?
![image](https://user-images.githubusercontent.com/61874432/97707796-c8e83100-1af2-11eb-8e8d-92bd7f876a30.png)

**Comment by anbergman** [comment]
Sorry, was some gitlab markdown confusion on my side. The link should work now.

**Comment by code-whale** [comment]
@anbergman ，Thank you for your patient help! 
I have started to run the automatic installation script, but the progress is slow due to network problems. 
After the installation is complete, I will try to install uppasd again, if there is a problem, I will come to ask you again! 
Thank you again for your help!

**Comment by anbergman** [comment]
Great, you can then contact me directly if you need further directions.

**Comment by code-whale** [comment]
@anbergman ,Sorry to bother you again. After I installed the osx compiler, I got the error shown in the figure below when I recompile. Do you know what this is? What should I do next? 
Are these errors because my computer is an amd graphics card? Does uppasd have to use cuda to simulate? Is it possible to use cpu?
![image](https://user-images.githubusercontent.com/61874432/97769578-10a8a000-1b67-11eb-85f9-ac1523dc8083.png)

**Comment by code-whale** [comment]
@anbergman ,I think the possible reason for the above error is that the gcc version does not match scipy, so I try to enter ````brew cask install gfortran````,But the following error occurred again, please correct me
![image](https://user-images.githubusercontent.com/61874432/97770936-cfb68880-1b72-11eb-8837-704c251b9803.png)
![image](https://user-images.githubusercontent.com/61874432/97770953-fc6aa000-1b72-11eb-9483-f0602aeabe2e.png)
