### ISSUE TITLE
GUI conda configuration is invalid

### ISSUE THREAD

**Issue by code-whale** [UppASD/UppASD#14]
@anbergman ,After I successfully compiled, I followed the conda method you posted on the homepage to configure the GUI, but after I executed ````conda install -c menpo enum```` and ````conda install -c qt5 pyqt5````
 the terminal reported an error as shown in the figure below. The first problem seems to be a version problem, and the second problem seems to be a problem with my conda configuration. Can you tell me how to solve this problem.
![image](https://user-images.githubusercontent.com/61874432/97799163-3c12b400-1c67-11eb-9def-874045772034.png)

**Comment by JPchico** [comment]
Hello @code-whale!
I think the issue is that the `enum` conda channel is only working with python 2.7 the simplest way is to install `enum` via the conda-forge channel which has compatibility to python3. You can do it by using the following
```
conda install -c conda-forge enum-compat
```

I'll update the `README.md` to clear up the inconsistency. Thanks for spotting the issue.

**Comment by code-whale** [comment]
@JPchico ,Thanks for your help, but the following error occurred when I used your command
![image](https://user-images.githubusercontent.com/61874432/97804578-ca992c80-1c8b-11eb-9c88-9192e827ad02.png)
![image](https://user-images.githubusercontent.com/61874432/97804586-d97fdf00-1c8b-11eb-99cf-d787b87b798d.png)
What caused the above error, I look forward to your reply! 
Are there other enum versions that can be substituted? 
I searched for your command on the conda website. The enum shown is applicable to the version before python3.4, and the python version configured in this env is 3.6. Will this have any effect? 
Thanks again for your help!

**Comment by JPchico** [comment]
Hello @code-whale 

That is interesting, I just tested in a fresh conda environment in linux and the installation went without a hitch
```
conda 4.8.5
Python 3.7.9
```

However, you are right in that the package is for back compatibility for python <3.4, it seems that `enum` was added to the standard in [python 3.4](https://www.python.org/dev/peps/pep-0435/)
So if you are using python >3.4 you **do not need to install enum**

**Comment by code-whale** [comment]
Hi,@JPchico ，Thanks again for your kind help! 
That is to say, I set env to python=3.6, and I no longer need to install enum. I am typing in the new pyqt command you changed in the pull request. The installation is slow due to network problems. I will test it after I install it! 
Is your updated pyqt command the same package as the original pyqt5? 
Because I noticed the code ````from pyqt5```` in ASD_GUI.py

**Comment by JPchico** [comment]
@code-whale , yes Qt5 is the new standard so when you install `pyqt` via the anaconda channel you get `pyqt-5.9.2`, so that should not be a problem.

If you have python3.6 or 3.7 it _should_ work without problems. Let me know how it goes!

**Comment by code-whale** [comment]
@JPchico ,Thank you for your patient help! 
I will tell you when there is progress in the next step! 
It is already night, I may need tomorrow to observe the next progress:)

**Comment by code-whale** [comment]
@JPchico ,Due to the slow online installation, I used the local installation method to successfully install pyqt. After the test, ASD_GUI can be displayed normally, as shown in the figure below. Thank you for your help. 
At the same time, enum does not need to be installed anymore (in the case of python=3.6 created by conda), there is no error when running ASD_GUI.py!
<img width="1274" alt="截屏2020-11-02 上午10 16 52" src="https://user-images.githubusercontent.com/61874432/97823619-8c842300-1cf4-11eb-9993-74b217789616.png">
I saw your pull request. I personally think that after using the ````conda create -name python 3.6 …..```` command, the subsequent ````conda install -c conda-forge enum-compat````  can no longer be added
This is just my own superficial opinion, my computer level is not high, please correct me if there is an error!

**Comment by JPchico** [comment]
@code-whale You are right! I have amended the pull request to reflect this.
