### ISSUE TITLE
Is it possible to utilize GPU in the initializaiton phase?

### ISSUE THREAD

**Issue by nujabse** [UppASD/UppASD#16]
When I set `gpumode 1` in the `inpsd.dat` file, UppASD only uses GPU when running the measurements. Is it possible to use GPU to accelarate the initialization phase?

**Comment by Deep2504** [comment]
Hi nujabse,

I am trying to get my GPU to work with UppASD, but I am unsure how. I am using Windows Subsystem for Linux, and when I try to use gfortran-cuda compiler, I get an error that ovf.h file is missing.

Have you encountered this issue? If you did, how did you resolve it?

I would appreciate your help.

Thank you!

Farhan

**Comment by Mahnaz-Rezaei** [comment]
Hi Deep2504,
I wanted to compile UppASD with gfortran-cuda. I have encountered the same errors as you. the errors are the following:
Third_party/ovf/src/ovf.cpp(1): catastrophic error: cannot open source file "ovf.h"
  #include "ovf.h"
                  ^
compilation aborted for Third_party/ovf/src/ovf.cpp (code 4)
make[2]: *** [Third_party/ovf/src/ovf.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [nocopyprofile] Error 2

Did you solve it? if you solve it, can you tell me how did you resolve it?
I'd appreciate any help you can offer.
Thanks.
mahnaz

**Comment by Deep2504** [comment]
Hi @Mahnaz-Rezaei 

No, I was not able to fix the issue.

**Comment by Mahnaz-Rezaei** [comment]
Thanks

**Comment by Mahnaz-Rezaei** [comment]
​Thanks

On Fri, 02/10/2023 11:20 PM, Deep2504 ***@***.***> wrote:
> 
Hi @Mahnaz-Rezaei
No, I was not able to fix the issue.

**Comment by johanhellsvik** [comment]
The first versions of CUDA backend for UppASD supported running on GPU only in measurements phase. This will be generalized so that also initial phase can be run on GPU.
