### ISSUE TITLE
gfortran Rank missmatch error

### ISSUE THREAD

**Issue by milton-persson** [UppASD/UppASD#19]
Had a compilation problem with gfortran on Debian:

Fetched UppASD with "git clone git://github.com/UppASD/UppASD.git".
Ran "make deps" and "./setup_UppASD.sh".

"make gfortran" then stopped with the following errors:
**Hamiltonian/fftdipole_mkl.f90:422:67:**

  417 |                   status  = DftiSetValue(handle,DFTI_PLACEMENT,DFTI_INPLACE)
      |                                                               2    
......
  422 |                   status  = DftiSetValue(handle,DFTI_INPUT_STRIDES,strides)
      |                                                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
**Hamiltonian/fftdipole_mkl.f90:330:64:**

  330 |                status  = DftiSetValue(handle,DFTI_INPUT_STRIDES,strides)
      |                                                                1
......
  417 |                   status  = DftiSetValue(handle,DFTI_PLACEMENT,DFTI_INPLACE)
      |                                                               2 
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
**Hamiltonian/fftdipole_mkl.f90:150:68:**

  150 |                   status  = DftiSetValue(handle,DFTI_BACKWARD_SCALE,1.0_dblprec/dble(Npadding))
      |                                                                    1
......
  417 |                   status  = DftiSetValue(handle,DFTI_PLACEMENT,DFTI_INPLACE)
      |                                                               2     
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
**Hamiltonian/fftdipole_mkl.f90:155:67:**

  155 |                   status  = DftiSetValue(handle,DFTI_INPUT_STRIDES,strides)
      |                                                                   1
......
  417 |                   status  = DftiSetValue(handle,DFTI_PLACEMENT,DFTI_INPLACE)
      |                                                               2    
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[2]: *** [Makefile:308: Hamiltonian/fftdipole_mkl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:148: copyprofile] Error 2
make[1]: Leaving directory '/home/milton/UppASD/source'
make: *** [Makefile:63: gfortran] Error 2

Problem fixed after adding "-fallow-argument-mismatch" to the list of flags in source/make/user_profiles/gfortran.make, as per Anders Bergman's instructions.

**Comment by UppASDadmin** [comment]
Thanks for reporting this @milton-persson . 
It was a known bug that was fixed for Mac OS but apparently also Ubuntu has now also updated their gfortran compilators.
