### ISSUE TITLE
compiling problem of uppASD

### ISSUE THREAD

**Issue by Tarek-Hammad-2010** [UppASD/UppASD#20]
Dear colleagues
I downloaded uppASD using the command https://github.com/UppASD/UppASD.git.
Then, I tried to compile the code using " make gfortran ", therefore the
compilation was crashed.
 my gfortran version is  " GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 ".
I attach here some screenshot to show what happened with me when trying to compile the code.
Thanks a lot for your help
Kind regards
Dr. Tarek Hammad.
![Screenshot from 2021-06-08 02-50-24](https://user-images.githubusercontent.com/85592581/121272924-6b596580-c8c7-11eb-852b-33533436995e.png)

**Comment by anbergman** [comment]
Hi Tarek,
This issue was caused by a recent commit that broke the compilation for gfortran<=8. 
It should now have been fixed with a bit more clever compilation checking in the makefiles.

**Comment by Tarek-Hammad-2010** [comment]
Hi Anders
Deep thanks for you. The problem has been fixed. I successfully compiled the code and I already practice its examples.
Kind regards.
Tarek Hammad.
