### ISSUE TITLE
Spin transfer torque

### ISSUE THREAD

**Issue by LLapsus** [UppASD/UppASD#21]
Hello,
is there an example how to properly setup spin transfer torque and spin orbit torque in UppASD?
I cannot find anything in the manual or examples folder.
Thank you.

**Comment by JPchico** [comment]
Hello! 

So the best solver to run STT is the Depondt solver `SDEalgh 5`, you also need to setup the spin polarized current acting over the cell, this is done with `jvec` which is a 3D vector `(jx, jy, jz)` in units of m/s. The higher your current the smaller the time step should be to ensure the numerical stability of the integration

If you want to take into account the non-adibatic parameter into account you need to set the `adibeta` parameter.

You can also set the polarization percentage of the current via `spin_pol` (going from 0-1) this would just re-scale the `jvec` value but it might be useful if you want to mimic an experimental situation.

If you also specify `alat` in the input (not needed) UppASD will try to evaluate the current density going through the material.

**Comment by LLapsus** [comment]
Hello, thank you for your help. I will try it.

**Comment by LLapsus** [comment]
Hello @JPchico ,
I had a try. First, to calculate spin transfer torque one needs to specify `stt  Y` in the inpsd.dat. Unfortunately, when I do it, I receive `forrtl: severe (174): SIGSEGV, segmentation fault occurred` error. To set STT I used parameters listed below. Do you have any idea what might be wrong? For more info I am providing inpsd.dat and the uppasd output. 
[files.zip](https://github.com/UppASD/UppASD/files/6726382/files.zip)
Thank you.

`
alat   1.0d-9  lattice constant (m)
aunits N
maptype 1

SDEalgh   5          

mode      S                              
stt       Y
temp      1.0
hfield    0.000 0.000 30.000       
damping   0.01
jvec      35.445807 0.000 0.000      

spin_pol  1.0
adibeta   0.1
`

**Comment by JPchico** [comment]
Hello @LLapsus yes I forgot about the `stt` keyword, if you want to use the stt based on the gradient of the magnetization, you should use  `stt A` instead of `stt Y`, that if I remember correctly is for a fixed layer polarizing the current and acting over a free magnetic layer.

I think that maybe that is the issue. I'd suggest that you try that. The input file looks reasonable, so it is either something with the `stt` option, or something with the setup of the system itself.

**Comment by LLapsus** [comment]
Hello @JPchico ,
I set `stt  A` and it runs now. Thank you.
