### ISSUE TITLE
Can't reproduce adiabatic magnon spectra for hcp Co

### ISSUE THREAD

**Issue by lpatra007** [UppASD/UppASD#23]
Hello UppASD developers

Firstly, thank you for developing such a code.

I am trying to reproduce some of the magnon spectra. I am able to do it for BCC Fe as well as FCC Co. However, when I am trying hcp systems e.g. hcp Co, I am unable to do it. I am unable to reproduce the Dirac cone (linear crossing) at the K-point (the reference figure is attached). I noticed someone reported such a mistake before and the developers replied that the issue has been resolved in the new issue. However, I am facing the same issue again. Can you find the mistake in my files? I have attached the input files. The exchange file has been generated using SPRKKR.

inpsd.dat
########################################################################
simid hcpConew
ncell     50        50       50               System size
BC        P         P         P                 Boundary conditions (0=vacuum, P=periodic

cell        1.0000000000        0.0000000000    0.0000000000
           -0.5000000000        0.8660254000    0.0000000000
            0.0000000000        0.0000000000    1.6028376100
Sym       0                                     Symmetry of lattice (0 for no, 1 for cubic, 2 for 2d cubic, 3 for hexagonal)
posfile   ./posfile
momfile   ./momfile
exchange  ./jASD2
maptype   2
SDEalgh   1                                     SDE solver: 1=midpoint, 2=heun, 3=heun3, 4=Heun_proper, 5=Depondt
Initmag   3                                     Initial config of moments (1=random, 2=cone, 3=spec., 4=file)
Mensemble 1
ip_mode   N                                     Initial phase parameters
ip_temp   1.0d-12                               --
ip_mcNstep     1
mode      S                                     S=SD, M=MC
temp      1.0d-12                               Measurement phase parameters
Nstep   1
damping 0.5
timestep 1.0e-16

do_ams Y
qpoints F                                       Flag for q-point generation (F=file,A=automatic,C=full cell)
qfile   ./qfile
do_magdos Y
########################################################
posfile
  1   1    0.3333     0.6667    0.2500
  2   1    0.6667     0.3333    0.7500
########################################################
momfile
1 1 1.5114 0.0 0.0 1.0
2 1 1.5114 0.0 0.0 1.0
########################################################

Thank you in advance for your help.
![hcp-Co-AMS](https://user-images.githubusercontent.com/69233553/147550899-54936d93-6ea3-407c-add1-7d1fc45bdf24.png)

**Comment by anbergman** [comment]
Hi @lpatra007,
It is hard to tell without your `jfile` if something is wrong, but it seems as your `posfile` is expressed in direct coordinates while the default format is cartesian coordinates. If you intend to use direct coordinates you need to specify `posfiletype D` in `inpsd.dat`. 

As a check on the hcp magnon bands I did a simulation with DFT Jij values and the following structural data: 
---inpsd.dat---
```
cell   0.8660254  -0.5000000   0.0000000
       0.0000000   1.0000000   0.0000000
       0.0000000   0.0000000   1.6166667
```
---posfile---
```
1  1 0.288675134595    0.500000000000    0.404166666667
2  1 0.577350269190    0.000000000000    1.212500000000
```
and the outcome shown below seems ok compared to your figure.

![image](https://user-images.githubusercontent.com/26410385/159578019-dc84a437-b394-405d-91f3-84fa58ccbfe7.png)

**Comment by lpatra007** [comment]
Thank you very much Dr. Bergman. I am able to fix the error.  There were mismatches between the coordinates types for posfile as well as qpoints file. I am able to get the figure as reported in the reference.
