### ISSUE TITLE
UppASD manual corrections

### ISSUE THREAD

**Issue by Fellow-baka** [UppASD/UppASD#3]
Where should I submit small fixes/corrections to UppASD manual (.pdf version)?

**Comment by JPchico** [comment]
Hello! Sorry for the very very late reply.

I think that you can make a pull request with any correction, fixes, etc. And then they can be added to the main branch

**Comment by UppASDadmin** [comment]
With the instructions given by @JPchico we can close this issue and look forward to future pull requests.
