### ISSUE TITLE
Heat bath error

### ISSUE THREAD

**Issue by LLapsus** [UppASD/UppASD#32]
Using heat bath Monte Carlo implemented in the latest UppASD version we were studying 2D Heisenberg model on a square lattice with Dzyaloshinskii-Moriya interaction (DMI). For various values of magnetic field (B) and DMI constant (D) we constructed a phase diagram. However, this diagram substantially differs from those published in the literature. Thus we did the same simulations with Metropolis algorithm, which gives phase diagram consistent with previous studies. We analyzed the heat bath implementation in UppASD and we believe we found a mistake in the subroutine flip_h. 

The phase diagrams obtained using heat bath and Metropolis algorithms are shown in the attached pdf file, where we also describe the potential issue in the code. We also show how the results change when the problematic piece of code is fixed.

[UppASD_heat_bath.pdf](https://github.com/UppASD/UppASD/files/9012858/UppASD_heat_bath.pdf)

**Comment by anbergman** [comment]
Dear @LLapsus,
Thanks for pointing this out. This bug was fixed in previous, non-official, versions of the code but have since a while also been available in the `github` version of the code as well. The implemented solution is not exactly the one you proposed but they should both be equivalent.
