### ISSUE TITLE
Neel Temprature

### ISSUE THREAD

**Issue by karvs25** [UppASD/UppASD#43]
Is it possible to calculate the Neel temperature using the UppASD code? If Yes, Can you tell me how to do it?

**Comment by anbergman** [comment]
Hi @karvs25 ,
Yes that is possible! The recommended way to do that would be to make a set of simulations for different temperatures, then extract the specific heat (Cv) for each temperature, and then plot Cv(T) where any phase transition you have in your system should be evident from peaks in the Cv(T) curve. This works for both Curie and Neél temperatures, i.e. it is indifferent to the magnetic order of your system. 

To measure the specific heat you need the flags 
```
plotenergy 1
do_cumu Y
```
in `inpsd.dat` and the results will be written to `cumulants.simid.out`. 

An example for a ferromagnet (bcc Fe) can be found in the folder `examples/PhaseDiagrams/bccFe-Tsweep` in the repository, where there are scripts that can be used to plot the specific heat as well as other relevant thermodynamic measurables.
