### ISSUE TITLE
How can I run  UppASD in parallel?

### ISSUE THREAD

**Issue by Mahnaz-Rezaei** [UppASD/UppASD#45]
Hi
I would like to run UppASD in parallel. I set the parallel option to '-DOMP' for using OpenMP in Makefile.gfortran file. Then I installed it following:
./setup_UppASD.sh  
 make gfortran
When I run UppASD in parallel, it does not run in parallel, the output of my system is repeated in the output file. Can you tell me how to do it?
Thank you.

**Comment by johanhellsvik** [comment]
Hi, thank you for reaching out.
Depending on the computer on which you are running, it will in general work to use the template source/make/default-profiles/gfortran.make without modification. On a laptop with Intel Core i7 and running Windows Subsystem for Linux 2, it the following worked out for a fresh clone of the UppASD repository

git clone https://github.com/UppASD/UppASD.git
cd UppASD/
./setup_UppASD.sh
make gfortran

In runtime you might need to 
export OMP_NUM_THREADS=<value>
in order to have the desired number of threads running. Sometimes this is set by default to the number of available cores.

**Comment by Mahnaz-Rezaei** [comment]
Thank you very much for your guidance.
I have to reduce the computational cost for simulation (because my system is large). I am trying to install UppASD on GPU. When I compile it using ifort-cuda compiler, I get the following errors:
#########################################################
Third_party/ovf/src/ovf.cpp(1): catastrophic error: cannot open source file "ovf.h"
#include "ovf.h"
^
compilation aborted for Third_party/ovf/src/ovf.cpp (code 4)
make[2]: *** [Third_party/ovf/src/ovf.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [nocopyprofile] Error 2
#######################################################
I defined the paths  in ovf.cpp file as follows:
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/ovf.h>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Filter_File_Handle.hpp>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Helpers.hpp>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/format.h>
######################################################
Then I got another error as follows:
/home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Filter_File_Handle.hpp(12): catastrophic error: cannot open source file "fmt/format.h"
  #include <fmt/format.h>
                         ^
compilation aborted for Third_party/ovf/src/ovf.cpp (code 4)
make[2]: *** [Third_party/ovf/src/ovf.o] Error 4
make[2]: *** Waiting for unfinished jobs....
gpu_files/cudaEventPool.hpp(15): warning: extended friend syntax is a C++11 feature
######################################################
Then I defined the paths  in Filter_File_Handle.hpp file as follows:
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/format.h>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/ostream.h>
####################################################
I  got a lot of errors.
Could you help me for resolving it?
I'd appreciate any help you can offer.
Thanks.
Mahnaz

**Comment by anbergman** [comment]
Marking this issue as resolved since the OpenMP question has been answered. 
For GPU compilation, please refer to #47.
