### ISSUE TITLE
Getting errors when installing UppASD on GPU ( using ifort-cuda compiler).

### ISSUE THREAD

**Issue by Mahnaz-Rezaei** [UppASD/UppASD#47]
Hi
 I am trying to install UppASD on GPU. When I compile it using ifort-cuda compiler, I get the following errors:
#########################################################
Third_party/ovf/src/ovf.cpp(1): catastrophic error: cannot open source file "ovf.h"
#include "ovf.h"
^
compilation aborted for Third_party/ovf/src/ovf.cpp (code 4)
make[2]: *** [Third_party/ovf/src/ovf.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [nocopyprofile] Error 2
#######################################################
I defined the paths in ovf.cpp file as follows:
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/ovf.h>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Filter_File_Handle.hpp>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Helpers.hpp>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/format.h>
######################################################
Then I got another error as follows:
/home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/detail/Filter_File_Handle.hpp(12): catastrophic error: cannot open source file "fmt/format.h"
#include <fmt/format.h>
^
compilation aborted for Third_party/ovf/src/ovf.cpp (code 4)
make[2]: *** [Third_party/ovf/src/ovf.o] Error 4
make[2]: *** Waiting for unfinished jobs....
gpu_files/cudaEventPool.hpp(15): warning: extended friend syntax is a C++11 feature
######################################################
Then I defined the paths in Filter_File_Handle.hpp file as follows:
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/format.h>
#include </home/m.rezaei.iasbs/UppASD/source/Third_party/ovf/include/fmt/ostream.h>
####################################################
I got a lot of errors.
Could you help me for resolving it?
I'd appreciate any help you can offer.
Thanks.
Mahnaz

**Comment by anbergman** [comment]
Dear @Mahnaz-Rezaei ,
First it should be stated that the GPU support in UppASD is limited to regular LLG dynamics i.e. `mode S` and that only a limited number of magnetic interactions and measurables are currently supported. There is however ongoing work on making the full code supported by GPU acceleration.
Still, it is possible to compile the code with this limited GPU support already now. For this I recommend to use our `cmake` based build system. This allows for automatic identification of CUDA versions and supported compute architectures as well as proper paths to libraries etc. 

With a recent update, the `cmake` approach should be possible to use for `gfortran` or `ifort` compilers  as follows:
```
FC=gfortran cmake -S . -B build -DUSE_CUDA=ON
cmake --build build --parallel
```
or 
```
FC=ifort cmake -S . -B build -DUSE_CUDA=ON
cmake --build build --parallel
```

The build system could be adapted for other compilers if needed, but since an overhaul of the GPU support is ongoing this is not prioritized at the moment.

**Comment by Mahnaz-Rezaei** [comment]
Thanks, I'll check it.

On Sat, 02/11/2023 02:06 PM, Anders Bergman ***@***.***> wrote:
> 
Dear @Mahnaz-Rezaei ,
> 
First it should be stated that the GPU support in UppASD is limited to regular LLG dynamics i.e. mode S and that only a limited number of magnetic interactions and measurables are currently supported. There is however ongoing work on making the full code supported by GPU acceleration.
> 
Still, it is possible to compile the code with this limited GPU support already now. For this I recommend to use our cmake based build system. This allows for automatic identification of CUDA versions and supported compute architectures as well as proper paths to libraries etc.
With a recent update, the cmake approach should be possible to use for gfortran or ifort compilers  as follows:
FC=gfortran cmake -S . -B build -DUSE_CUDA=ON
cmake --build build --parallel

or
FC=ifort cmake -S . -B build -DUSE_CUDA=ON
cmake --build build --parallel

The build system could be adapted for other compilers if needed, but since an overhaul of the GPU support is ongoing this is not prioritized at the moment.

**Comment by Mahnaz-Rezaei** [comment]
Dear Anders Bergman,
I did the cmake approach for compiling as you told me. The first step was executed and the build folder was created. But the second step was not complete and I got some errors as follows:
Scanning dependencies of target asdlib
[  0%] Building Fortran object CMakeFiles/asdlib.dir/source/Parameters/parameters.f90.o
[  1%] Building Fortran object CMakeFiles/asdlib.dir/source/RNG/stdtypes.f90.o
[  2%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o
[  3%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/lsqrDataModule.f90.o
[  4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/ddot__genmod.f90.o
[  4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dnrm2__genmod.f90.o
[  5%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dscal__genmod.f90.o
[  6%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/interpolation.f90.o
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.21:

     call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                     1
Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.36:

     call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                                    1
Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.23:

        call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                       1
Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.38:

        call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                                      1
Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.21:

    call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                     1
Error: Internal procedure 'compare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.30:

    call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                              1
Error: Internal procedure 'swap' is not allowed as an actual argument at (1)
gmake[2]: *** [CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/asdlib.dir/all] Error 2

Could you help me for resolving it?
I'd appreciate any help you can offer.
Thanks.
Mahnaz

**Comment by Mahnaz-Rezaei** [comment]
​Dear Anders Bergman,
I did the cmake approach for compiling as you told me. I used the following steps:
1: FC=gfortran cmake -S . -B build -DUSE_CUDA=ON
2: cmake --build build --parallel
The first step was executed and the build folder was created. But the second step was not complete and I got some errors as follows:
Scanning dependencies of target asdlib
[ 0%] Building Fortran object CMakeFiles/asdlib.dir/source/Parameters/parameters.f90.o
[ 1%] Building Fortran object CMakeFiles/asdlib.dir/source/RNG/stdtypes.f90.o
[ 2%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o
[ 3%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/lsqrDataModule.f90.o
[ 4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/ddot__genmod.f90.o
[ 4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dnrm2__genmod.f90.o
[ 5%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dscal__genmod.f90.o
[ 6%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/interpolation.f90.o
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.21:


 call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                 1



Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.36:


 call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                                1



Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.23:


    call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                   1



Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.38:


    call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                                  1



Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.21:


call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                 1



Error: Internal procedure 'compare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.30:


call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                          1



Error: Internal procedure 'swap' is not allowed as an actual argument at (1)
gmake[2]: *** [CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/asdlib.dir/all] Error 2
Could you help me for resolving it?
I'd appreciate any help you can offer.
Thanks.
Mahnaz

**Comment by Mahnaz-Rezaei** [comment]
Dear Anders Bergman,
I did the cmake approach for compiling as you told me. I used the following steps:
1: FC=gfortran cmake -S . -B build -DUSE_CUDA=ON
2: cmake --build build --parallel
The first step was executed and the build folder was created. But the second step was not complete and I got some errors as follows:
Scanning dependencies of target asdlib
[ 0%] Building Fortran object CMakeFiles/asdlib.dir/source/Parameters/parameters.f90.o
[ 1%] Building Fortran object CMakeFiles/asdlib.dir/source/RNG/stdtypes.f90.o
[ 2%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o
[ 3%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/lsqrDataModule.f90.o
[ 4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/ddot__genmod.f90.o
[ 4%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dnrm2__genmod.f90.o
[ 5%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/dscal__genmod.f90.o
[ 6%] Building Fortran object CMakeFiles/asdlib.dir/source/Multiscale/interpolation.f90.o
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.21:

 call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                 1
Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:180.36:

 call build_heap(offsetCompare, offsetSwap,1,1+endIndex-startIndex)
                                1
Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.23:

    call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                   1
Error: Internal procedure 'offsetcompare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:186.38:

    call down_heap(offsetCompare, offsetSwap,1,1+last-startIndex)
                                  1
Error: Internal procedure 'offsetswap' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.21:

call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                 1
Error: Internal procedure 'compare' is not allowed as an actual argument at (1)
/home/m.rezaei.iasbs/mr/UppASD/source/Multiscale/sortmodule.f90:69.30:

call sortGeneric(compare, swap, 1, ubound(intArray, 1))
                          1
Error: Internal procedure 'swap' is not allowed as an actual argument at (1)
gmake[2]: *** [CMakeFiles/asdlib.dir/source/Multiscale/sortmodule.f90.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/asdlib.dir/all] Error 2

Could you help me for resolving it?
I'd appreciate any help you can offer.
Thanks.
Mahnaz

**Comment by anbergman** [comment]
Dear Mahnaz,
This error is actually not directly connected to the GPU-enabled compiling since the complaints seem to occur in the multiscale part of the code where no CUDA routines are in play. 
Instead the error messages indicate that your compiler is not accepting the Fortran 2008-style coding that is used in this part of the code. This is a bit unexpected since most "modern" compilers (i.e. gfortran>9.0) should support Fortran 2008 syntax so I would advice you to try a more up-to-date compiler in case that would help. 
See https://stackoverflow.com/questions/9982657/passing-an-internal-procedure-as-argument for reference.

**Comment by Mahnaz-Rezaei** [comment]
Thanks.
