### ISSUE TITLE
Tensorial input order

### ISSUE THREAD

**Issue by SiposMB** [UppASD/UppASD#78]
Hi!

I'm an undergrad student working on Curie temperature simulation.
I'm wondering how the tensorial input file is set up. Is the order of the coefficients the same as for the anisotropic exchange coupling (J_xx J_yy J_zz J_xy J_xz J_yz) or having nine components does it take the more tipical row-wise input (J_xx J_xy J_xz J_yx J_yy J_yz J_zx J_zy J_zz)? 

Marcell

**Comment by SiposMB** [comment]
I found the method in the source code (inputhandler_ext.f90), and it's J_xx, J_xy, J_xz, and so on.

**Comment by SiposMB** [comment]
I found the method in the source code (inputhandler_ext.f90, read_exchange_tensor_base), and it's J_xx, J_xy, J_xz, and so on.

**Comment by anbergman** [comment]
Hi @SiposMB ,
Good thing you managed to figure it out from the source. The format is indeed supposed to be 
`[J_xx J_xy J_xz J_yx J_yy J_yz J_zx J_zy J_zz]`
The manual is a bit spotty in that section so we will update it. Also note that the energy unit for that file is the same as all other exchange interaction inputs, i.e. mRy/atom and nothing else (once again the manual will be updated).
